name: ci-cd
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Update Databricks Repo to latest
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          REPO_PATH: ${{ secrets.REPO_PATH }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          CLEAN_PATH=$(echo "$REPO_PATH" | tr -d '"' | xargs)
          echo "Using REPO_PATH: '$CLEAN_PATH'"
          databricks repos update --path "$CLEAN_PATH" --branch "$GITHUB_REF_NAME"