name: ci-cd
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-databricks-cli@v1

      - name: Configure Databricks auth (PAT)
        run: databricks configure --host "$DATABRICKS_HOST" --token "$DATABRICKS_TOKEN"
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      - name: Update Databricks Repo to latest
        run: databricks repos update --path "${REPO_PATH}" --branch "${GITHUB_REF_NAME}"
        env:
          REPO_PATH: ${{ secrets.REPO_PATH }}

